/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import static classes.BillGenerate.datatable;
import java.awt.Toolkit;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Sakshi
 */
public class Accounts extends javax.swing.JFrame {

    /**
     * Creates new form Accounts
     */
    public Accounts() {
        initComponents();
        
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
     panel_dealer.setVisible(false);
     salsepanel.setVisible(false);
     discountpanel.setVisible(false);
     pgstpanel.setVisible(false);
     sgstpanel.setVisible(false);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    public void excelSheet(){
          FileOutputStream fos = null;
          BufferedOutputStream bos = null;
          XSSFWorkbook excelJTableExporter = null;
        
        JFileChooser jfc = new JFileChooser("C:\\Users\\Sakshi\\Desktop");
        jfc.setDialogTitle("Save As");
        
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls");
        jfc.setFileFilter(fnef);
        int excelChooser =  jfc.showSaveDialog(null);
      
        
      
     
        
                
        if(excelChooser == JFileChooser.APPROVE_OPTION){
       
            try {
                excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable sheet");
                for(int i = 0 ; i < purchasetable.getRowCount() ; i++){
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for(int j = 0 ; j <  purchasetable.getColumnCount() ; j++){
                        XSSFCell excelCell = excelRow.createCell(j);
                        
                         
                        excelCell.setCellValue(purchasetable.getValueAt(i, j).toString());
                      
                    }
                    
                }     fos = new FileOutputStream(jfc.getSelectedFile() + ".xls");
                 bos = new BufferedOutputStream(fos);
                excelJTableExporter.write(bos);
                JOptionPane.showMessageDialog(null, "Exported successfully...");
            } catch (FileNotFoundException ex) {
               ex.printStackTrace();
            }  catch (IOException ex) {
                   ex.printStackTrace();
               } finally {
                try {
                      if(bos != null){
                           bos.close();
                    }
                    if(fos != null){
                           fos.close();
                    }
                  
                     if(excelJTableExporter != null){
                           excelJTableExporter.close();
                    }
                 
                } catch (IOException ex) {
                   ex.printStackTrace();
                }
            }
          
          
          
          
      }
    }
    
    
        
      
       //show mrp method
    public void showSGST() {
        try { 
            
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();
            
             SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
             String start_date = d.format(pgststartdate.getDate());
             String end_date = d.format(pgstenddate.getDate());
       
            
            String query = "select sum(sgst) from products  WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'" ;
         
            ResultSet rs = Connect.st.executeQuery(query);
         
            while (rs.next()) {
                String sgst = Double.toString(rs.getDouble(1));
                totalsgstlbl.setText(sgst);
            }
            
//            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }
    
     public void showCGST() {
        try { 
            
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();
            
             SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
             String start_date = d.format(pgststartdate.getDate());
             String end_date = d.format(pgstenddate.getDate());
       
            
            String query = "select sum(cgst) from products  WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'" ;
         
            ResultSet rs = Connect.st.executeQuery(query);
         
            while (rs.next()) {
                String sgst = Double.toString(rs.getDouble(1));
                totalcgstlbl.setText(sgst);
            }
            
//            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }
   
            
     public void showSGSTSell() {
        try { 
            
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();
            
             SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
             String start_date = d.format(sgststaartdate.getDate());
             String end_date = d.format(sgstenddate.getDate());
       
            
            String query = "select sum(sgst) from sellproducts  WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'" ;
         
            ResultSet rs = Connect.st.executeQuery(query);
         
            while (rs.next()) {
                String sgst = Double.toString(rs.getDouble(1));
                totalsellsgst.setText(sgst);
            }
            
//            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }
    
     public void showCGSTSell() {
        try { 
            
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();
            
             SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
             String start_date = d.format(sgststaartdate.getDate());
             String end_date = d.format(sgstenddate.getDate());
       
            
            String query = "select sum(cgst) from sellproducts  WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'" ;
         
            ResultSet rs = Connect.st.executeQuery(query);
         
            while (rs.next()) {
                String cgst = Double.toString(rs.getDouble(1));
                totalsellcgst.setText(cgst);
            }
            
//            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }
   
            
    
     
    
       
    
    
    
    
      
    
    void showPurchasedProducts(){
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String start_date = d.format(DayProStart.getDate());
        String end_date = d.format(DayProEnd.getDate());
       
        
        String query_show_product_details = "SELECT product_name as Product, hsn_number as HSN, quantity as Quantity, product_price as Price, total_price as TotalPrice, sgst as SGST, cgst as CGST, sgstamt as SGSTAmt, cgstamt as CGSTAmt, total_scgst_amt as TotalGST, total_price_scgst as GrandTotal, destributor as Dealer, Bill_no as Bill, External_invoice as Invoice FROM `products` WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'";
        try{
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();

            ResultSet rs = Connect.st.executeQuery(query_show_product_details);

            purchasetable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
        
    }
    
      
    void showDiscountsTable(){
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String start_date = d.format(startdate.getDate());
        String end_date = d.format(enddate.getDate());
       
        
        String query_show_product_details = "SELECT billno as Bill, total as Total, discount_in_per as Discount, discount_in_amt as DiscountAmt, final_grand_total as GrandTotal FROM `perdiscount` WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'";
        try{
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();

            ResultSet rs = Connect.st.executeQuery(query_show_product_details);

            purchasetable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
        
    }
    
    
     void showSellProducts(){
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String start_date = d.format(sellprodsdate.getDate());
        String end_date = d.format(sellprodedate.getDate());
     
        
        String query_show_product_details = "SELECT billno as Bill, product_name as Product, hsn_number as HSN, quantity as Quantity, mrp as MRP, total_mrp_of_prod as TotalMrp, sgst as SGST, sgstamt as SGSTAmt, cgst as CGST, cgstamt as CGSTAmt, total_price_scgst as GrandTotal,customer_name as Customer, cust_contact_no as ContactNo  FROM `sellproducts` WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'";
        try{
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();

            ResultSet rs = Connect.st.executeQuery(query_show_product_details);

            purchasetable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(ClassNotFoundException | SQLException e){
             JOptionPane.showMessageDialog(null, "No record in this table"); 
        }
        
    }
     
      void showPurchasedGST(){
         SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String start_date = d.format(pgststartdate.getDate());
        String end_date = d.format(pgstenddate.getDate());
       
        
        String query_show_product_details = "SELECT Bill_no as Bill, External_invoice as Invoice, product_name as Product, quantity as Quantity, sgst as SGST, cgst as CGST, destributor as Dealer FROM `products` WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'";
        try{
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();

            ResultSet rs = Connect.st.executeQuery(query_show_product_details);

            purchasetable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
        
        
    }
      
        void showSalledGST(){
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String start_date = d.format(sgststaartdate.getDate());
        String end_date = d.format(sgstenddate.getDate());
     
        
        String query_show_product_details = "SELECT billno as Bill, product_name as Product, quantity as Quantity, sgst as SGST, cgst as CGST, sgstamt as SGSTAmt, cgstamt as CGSTAmt  FROM `sellproducts` WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'";
        try{
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();

            ResultSet rs = Connect.st.executeQuery(query_show_product_details);

            purchasetable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
        
    }
     
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainmenus = new javax.swing.JPanel();
        addlogolbl = new javax.swing.JLabel();
        addlbl = new javax.swing.JLabel();
        selllogolbl = new javax.swing.JLabel();
        sellblb = new javax.swing.JLabel();
        orderlogo = new javax.swing.JLabel();
        orderlbl = new javax.swing.JLabel();
        showlogo = new javax.swing.JLabel();
        showlbl = new javax.swing.JLabel();
        showlbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        salsepanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sellprodedate = new com.toedter.calendar.JDateChooser();
        sellprodsdate = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        purchasetable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panel_dealer = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        DayProEnd = new com.toedter.calendar.JDateChooser();
        DayProStart = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        searchboxtxt = new javax.swing.JTextField();
        discountpanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        startdate = new com.toedter.calendar.JDateChooser();
        enddate = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        sgstpanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        sgststaartdate = new com.toedter.calendar.JDateChooser();
        sgstenddate = new com.toedter.calendar.JDateChooser();
        jButton10 = new javax.swing.JButton();
        pgstpanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pgststartdate = new com.toedter.calendar.JDateChooser();
        pgstenddate = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalcgstlbl = new javax.swing.JLabel();
        totalsgstlbl = new javax.swing.JLabel();
        totalsellsgst = new javax.swing.JLabel();
        totalsellcgst = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainmenus.setBackground(new java.awt.Color(150, 150, 165));

        addlogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addlogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlogolblMouseClicked(evt);
            }
        });

        addlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addlbl.setForeground(new java.awt.Color(0, 0, 0));
        addlbl.setText("   Add");
        addlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlblMouseClicked(evt);
            }
        });

        selllogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart-of-checkered-design.png"))); // NOI18N
        selllogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selllogolblMouseClicked(evt);
            }
        });

        sellblb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sellblb.setForeground(new java.awt.Color(0, 0, 0));
        sellblb.setText("    Sell");
        sellblb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellblbMouseClicked(evt);
            }
        });

        orderlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bag.png"))); // NOI18N
        orderlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlogoMouseClicked(evt);
            }
        });

        orderlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderlbl.setForeground(new java.awt.Color(0, 0, 0));
        orderlbl.setText(" Order");
        orderlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlblMouseClicked(evt);
            }
        });

        showlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        showlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlogoMouseClicked(evt);
            }
        });

        showlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl.setForeground(new java.awt.Color(0, 0, 0));
        showlbl.setText("  Shwo");
        showlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlblMouseClicked(evt);
            }
        });

        showlbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl1.setForeground(new java.awt.Color(0, 0, 0));
        showlbl1.setText(" Account");
        showlbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlbl1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money.png"))); // NOI18N

        javax.swing.GroupLayout mainmenusLayout = new javax.swing.GroupLayout(mainmenus);
        mainmenus.setLayout(mainmenusLayout);
        mainmenusLayout.setHorizontalGroup(
            mainmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenusLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(mainmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addlogolbl)
                        .addComponent(orderlogo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(addlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellblb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selllogolbl)
                        .addComponent(orderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showlogo)
                        .addComponent(showlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(showlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        mainmenusLayout.setVerticalGroup(
            mainmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenusLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(addlogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addlbl)
                .addGap(18, 18, 18)
                .addComponent(selllogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellblb)
                .addGap(18, 18, 18)
                .addComponent(orderlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderlbl)
                .addGap(18, 18, 18)
                .addComponent(showlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showlbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showlbl1)
                .addGap(53, 53, 53))
        );

        getContentPane().add(mainmenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        bg.setBackground(new java.awt.Color(43, 27, 61));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(150, 150, 165));

        jButton14.setBackground(new java.awt.Color(150, 150, 165));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1123, Short.MAX_VALUE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 50));

        salsepanel.setBackground(new java.awt.Color(43, 27, 61));
        salsepanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Starting Date");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Ending Date");

        sellprodedate.setBackground(new java.awt.Color(43, 27, 61));
        sellprodedate.setDateFormatString("yyyy-MM-dd");

        sellprodsdate.setBackground(new java.awt.Color(43, 27, 61));
        sellprodsdate.setDateFormatString("yyyy-MM-dd");

        jButton2.setBackground(new java.awt.Color(43, 27, 61));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setText("Show");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salsepanelLayout = new javax.swing.GroupLayout(salsepanel);
        salsepanel.setLayout(salsepanelLayout);
        salsepanelLayout.setHorizontalGroup(
            salsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salsepanelLayout.createSequentialGroup()
                .addGroup(salsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salsepanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(salsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(salsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sellprodsdate, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(sellprodedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(salsepanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        salsepanelLayout.setVerticalGroup(
            salsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salsepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellprodsdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(salsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellprodedate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(salsepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 350, 150));

        purchasetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(purchasetable);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 1100, 170));

        jButton1.setBackground(new java.awt.Color(43, 27, 61));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Discounts");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 100, 30));

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setText("Purchased");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        bg.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 100, 30));

        jButton4.setBackground(new java.awt.Color(43, 27, 61));
        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 0));
        jButton4.setText("Selled");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        bg.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 120, 30));

        panel_dealer.setBackground(new java.awt.Color(43, 27, 61));
        panel_dealer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Starting Date");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ending Date");

        DayProEnd.setBackground(new java.awt.Color(43, 27, 61));
        DayProEnd.setDateFormatString("yyyy-MM-dd");

        DayProStart.setBackground(new java.awt.Color(43, 27, 61));
        DayProStart.setDateFormatString("yyyy-MM-dd");

        jButton5.setBackground(new java.awt.Color(43, 27, 61));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 0));
        jButton5.setText("Show");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dealerLayout = new javax.swing.GroupLayout(panel_dealer);
        panel_dealer.setLayout(panel_dealerLayout);
        panel_dealerLayout.setHorizontalGroup(
            panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dealerLayout.createSequentialGroup()
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dealerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DayProStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(DayProEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_dealerLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel_dealerLayout.setVerticalGroup(
            panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dealerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DayProStart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DayProEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(panel_dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 360, 150));

        searchboxtxt.setBackground(new java.awt.Color(43, 27, 61));
        searchboxtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        searchboxtxt.setForeground(new java.awt.Color(255, 255, 255));
        searchboxtxt.setText("Search here");
        searchboxtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        searchboxtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchboxtxtMouseClicked(evt);
            }
        });
        searchboxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxtxtActionPerformed(evt);
            }
        });
        searchboxtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxtxtKeyReleased(evt);
            }
        });
        bg.add(searchboxtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, 160, 30));

        discountpanel.setBackground(new java.awt.Color(43, 27, 61));
        discountpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Starting Date");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Ending Date");

        startdate.setBackground(new java.awt.Color(43, 27, 61));

        enddate.setBackground(new java.awt.Color(43, 27, 61));

        jButton6.setBackground(new java.awt.Color(43, 27, 61));
        jButton6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 0));
        jButton6.setText("Show");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout discountpanelLayout = new javax.swing.GroupLayout(discountpanel);
        discountpanel.setLayout(discountpanelLayout);
        discountpanelLayout.setHorizontalGroup(
            discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startdate, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(enddate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discountpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        discountpanelLayout.setVerticalGroup(
            discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(enddate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(discountpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 330, 150));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GST");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 1100, 30));

        jButton8.setBackground(new java.awt.Color(43, 27, 61));
        jButton8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 153, 0));
        jButton8.setText("Sell GST");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        bg.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 150, 30));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 153, 0));
        jButton9.setText("Purchased GST");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        bg.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 30));

        sgstpanel.setBackground(new java.awt.Color(43, 27, 61));
        sgstpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Starting Date");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Ending Date");

        sgststaartdate.setBackground(new java.awt.Color(43, 27, 61));

        sgstenddate.setBackground(new java.awt.Color(43, 27, 61));

        jButton10.setBackground(new java.awt.Color(43, 27, 61));
        jButton10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 153, 0));
        jButton10.setText("Show");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sgstpanelLayout = new javax.swing.GroupLayout(sgstpanel);
        sgstpanel.setLayout(sgstpanelLayout);
        sgstpanelLayout.setHorizontalGroup(
            sgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sgstpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(sgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sgststaartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sgstenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(sgstpanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sgstpanelLayout.setVerticalGroup(
            sgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgstpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sgststaartdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sgstenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(sgstpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 350, 140));

        pgstpanel.setBackground(new java.awt.Color(43, 27, 61));
        pgstpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Starting Date");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Ending Date");

        pgststartdate.setBackground(new java.awt.Color(43, 27, 61));

        pgstenddate.setBackground(new java.awt.Color(43, 27, 61));

        jButton11.setBackground(new java.awt.Color(43, 27, 61));
        jButton11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 153, 0));
        jButton11.setText("Show");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pgstpanelLayout = new javax.swing.GroupLayout(pgstpanel);
        pgstpanel.setLayout(pgstpanelLayout);
        pgstpanelLayout.setHorizontalGroup(
            pgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgstpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(pgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pgststartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgstenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(pgstpanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pgstpanelLayout.setVerticalGroup(
            pgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgstpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pgststartdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pgstpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgstenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(pgstpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 350, 140));

        jPanel1.setBackground(new java.awt.Color(43, 27, 61));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SGST");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CGST");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Puechased");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salled");

        totalcgstlbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalcgstlbl.setForeground(new java.awt.Color(255, 255, 255));
        totalcgstlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalcgstlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalsgstlbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalsgstlbl.setForeground(new java.awt.Color(255, 255, 255));
        totalsgstlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalsgstlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalsellsgst.setForeground(new java.awt.Color(255, 255, 255));
        totalsellsgst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalsellcgst.setForeground(new java.awt.Color(255, 255, 255));
        totalsellcgst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalcgstlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalsellcgst, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalsgstlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalsellsgst, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(totalsellsgst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalsgstlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(totalsellcgst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(totalcgstlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 310, 160));

        jButton7.setBackground(new java.awt.Color(43, 27, 61));
        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 0));
        jButton7.setText("Export");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        bg.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 140, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1160, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addlogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlogolblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        PurchaseProducts pp = new PurchaseProducts();
        pp.setVisible(true);
    }//GEN-LAST:event_addlogolblMouseClicked

    private void addlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        PurchaseProducts pp = new PurchaseProducts();
        pp.setVisible(true);

    }//GEN-LAST:event_addlblMouseClicked

    private void selllogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selllogolblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SellProducts ss = new SellProducts();
        ss.setVisible(true);
    }//GEN-LAST:event_selllogolblMouseClicked

    private void sellblbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellblbMouseClicked
        // TODO add your handling code here:
         this.dispose();
        SellProducts ss = new SellProducts();
        ss.setVisible(true);
    }//GEN-LAST:event_sellblbMouseClicked

    private void orderlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlogoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        OrderProduct op = new OrderProduct();
        op.setVisible(true);
    }//GEN-LAST:event_orderlogoMouseClicked

    private void orderlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        OrderProduct op = new OrderProduct();
        op.setVisible(true);
    }//GEN-LAST:event_orderlblMouseClicked

    private void showlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlogoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ShowProducts sp = new ShowProducts();
        sp.setVisible(true);
    }//GEN-LAST:event_showlogoMouseClicked

    private void showlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlblMouseClicked
        // TODO add your handling code here:
           this.dispose();
        ShowProducts sp = new ShowProducts();
        sp.setVisible(true);
    }//GEN-LAST:event_showlblMouseClicked

    private void showlbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showlbl1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
  
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      showSellProducts();   
     
               
       
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          sgstpanel.setVisible(false);
        pgstpanel.setVisible(false);
        
        salsepanel.setVisible(false);
         discountpanel.setVisible(false);
        panel_dealer.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        showPurchasedProducts();
        showSGST();
        showCGST();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sgstpanel.setVisible(false);
        pgstpanel.setVisible(false);
        
        panel_dealer.setVisible(false);
        discountpanel.setVisible(false);
        salsepanel.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchboxtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchboxtxtMouseClicked
        // TODO add your handling code here:
        searchboxtxt.setText("");
    }//GEN-LAST:event_searchboxtxtMouseClicked

    private void searchboxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxtxtActionPerformed

    private void searchboxtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxtxtKeyReleased
        // TODO add your handling code here:
        
        DefaultTableModel table =  (DefaultTableModel)purchasetable.getModel();
        String search = searchboxtxt.getText();
        TableRowSorter<DefaultTableModel> tr = new  TableRowSorter<DefaultTableModel>(table);
        purchasetable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));

    }//GEN-LAST:event_searchboxtxtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sgstpanel.setVisible(false);
        pgstpanel.setVisible(false);
        
                salsepanel.setVisible(false);
           panel_dealer.setVisible(false);
        discountpanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         showDiscountsTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         salsepanel.setVisible(false);
           panel_dealer.setVisible(false);
        discountpanel.setVisible(false);
        
        
        pgstpanel.setVisible(false);
        sgstpanel.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         showSalledGST();
           showSGSTSell();
          showCGSTSell();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        showPurchasedGST();
        showSGST();
        showCGST();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          salsepanel.setVisible(false);
           panel_dealer.setVisible(false);
        discountpanel.setVisible(false);
        
        sgstpanel.setVisible(false);
        pgstpanel.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        excelSheet();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DayProEnd;
    private com.toedter.calendar.JDateChooser DayProStart;
    private javax.swing.JLabel addlbl;
    private javax.swing.JLabel addlogolbl;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel discountpanel;
    private com.toedter.calendar.JDateChooser enddate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainmenus;
    private javax.swing.JLabel orderlbl;
    private javax.swing.JLabel orderlogo;
    private javax.swing.JPanel panel_dealer;
    private com.toedter.calendar.JDateChooser pgstenddate;
    private javax.swing.JPanel pgstpanel;
    private com.toedter.calendar.JDateChooser pgststartdate;
    private javax.swing.JTable purchasetable;
    private javax.swing.JPanel salsepanel;
    private javax.swing.JTextField searchboxtxt;
    private javax.swing.JLabel sellblb;
    private javax.swing.JLabel selllogolbl;
    private com.toedter.calendar.JDateChooser sellprodedate;
    private com.toedter.calendar.JDateChooser sellprodsdate;
    private com.toedter.calendar.JDateChooser sgstenddate;
    private javax.swing.JPanel sgstpanel;
    private com.toedter.calendar.JDateChooser sgststaartdate;
    private javax.swing.JLabel showlbl;
    private javax.swing.JLabel showlbl1;
    private javax.swing.JLabel showlogo;
    private com.toedter.calendar.JDateChooser startdate;
    private javax.swing.JLabel totalcgstlbl;
    private javax.swing.JLabel totalsellcgst;
    private javax.swing.JLabel totalsellsgst;
    private javax.swing.JLabel totalsgstlbl;
    // End of variables declaration//GEN-END:variables
}
