/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Toolkit;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Sakshi
 */
public class OrderProduct extends javax.swing.JFrame {

    /**
     * Creates new form OrderProduct
     */
    public OrderProduct() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        newprodaddpanel.setVisible(false);
        newprodaddpanel1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
               
                 
    public void excelSheet(){
          FileOutputStream fos = null;
          BufferedOutputStream bos = null;
          XSSFWorkbook excelJTableExporter = null;
        
        JFileChooser jfc = new JFileChooser("C:\\Users\\Sakshi\\Desktop");
        jfc.setDialogTitle("Save As");
        
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls");
        jfc.setFileFilter(fnef);
        int excelChooser =  jfc.showSaveDialog(null);
      
        
      
     
        
                
        if(excelChooser == JFileChooser.APPROVE_OPTION){
       
            try {
                excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable sheet");
                for(int i = 0 ; i < mytable.getRowCount() ; i++){
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for(int j = 0 ; j <  mytable.getColumnCount() ; j++){
                        XSSFCell excelCell = excelRow.createCell(j);
                        
                         
                        excelCell.setCellValue(mytable.getValueAt(i, j).toString());
                      
                    }
                    
                }     fos = new FileOutputStream(jfc.getSelectedFile() + ".xls");
                 bos = new BufferedOutputStream(fos);
                excelJTableExporter.write(bos);
                JOptionPane.showMessageDialog(null, "Exported successfully...");
            } catch (FileNotFoundException ex) {
               ex.printStackTrace();
            }  catch (IOException ex) {
                   ex.printStackTrace();
               } finally {
                try {
                      if(bos != null){
                           bos.close();
                    }
                    if(fos != null){
                           fos.close();
                    }
                  
                     if(excelJTableExporter != null){
                           excelJTableExporter.close();
                    }
                 
                } catch (IOException ex) {
                   ex.printStackTrace();
                }
            }
          
          
          
          
      }
    }
    
              
               
               
    
     // show table of order products.
       void showtable() throws ClassNotFoundException{
         
        String sql="select product_name,quantity,destributor,date from orderdata";
        try 
        {
               Class.forName(Connect.myDriver);
                Connect.con = DriverManager.getConnection(Connect.url,"","");
                Connect.st = Connect.con.createStatement();
            ResultSet rs=Connect.st.executeQuery(sql);
            mytable.setModel(DbUtils.resultSetToTableModel(rs));
        } 
        catch (SQLException e) 
        {
          JOptionPane.showMessageDialog(this, "No record in this table");  
            
        }   
         }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menupanel = new javax.swing.JPanel();
        addlogolbl = new javax.swing.JLabel();
        addlbl = new javax.swing.JLabel();
        selllogolbl = new javax.swing.JLabel();
        sellblb = new javax.swing.JLabel();
        orderlogo = new javax.swing.JLabel();
        orderlbl = new javax.swing.JLabel();
        showlogo = new javax.swing.JLabel();
        showlbl = new javax.swing.JLabel();
        showlbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        orderproductpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        orderproductname = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        orderquantity = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        orderdealer = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        newprodaddpanel = new javax.swing.JPanel();
        newdealeradd = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        newprodaddpanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        newprodadd = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setBackground(new java.awt.Color(150, 150, 165));

        addlogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addlogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlogolblMouseClicked(evt);
            }
        });

        addlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addlbl.setForeground(new java.awt.Color(0, 0, 0));
        addlbl.setText("   Add");
        addlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlblMouseClicked(evt);
            }
        });

        selllogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart-of-checkered-design.png"))); // NOI18N
        selllogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selllogolblMouseClicked(evt);
            }
        });

        sellblb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sellblb.setForeground(new java.awt.Color(0, 0, 0));
        sellblb.setText("    Sell");
        sellblb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellblbMouseClicked(evt);
            }
        });

        orderlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bag.png"))); // NOI18N
        orderlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlogoMouseClicked(evt);
            }
        });

        orderlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderlbl.setForeground(new java.awt.Color(0, 0, 0));
        orderlbl.setText(" Order");
        orderlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlblMouseClicked(evt);
            }
        });

        showlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        showlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlogoMouseClicked(evt);
            }
        });

        showlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl.setForeground(new java.awt.Color(0, 0, 0));
        showlbl.setText("  Shwo");
        showlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlblMouseClicked(evt);
            }
        });

        showlbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl1.setForeground(new java.awt.Color(0, 0, 0));
        showlbl1.setText(" Account");
        showlbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlbl1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addlogolbl)
                        .addComponent(orderlogo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(addlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellblb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selllogolbl)
                        .addComponent(orderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showlogo)
                        .addComponent(showlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(showlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(addlogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addlbl)
                .addGap(18, 18, 18)
                .addComponent(selllogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellblb)
                .addGap(18, 18, 18)
                .addComponent(orderlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderlbl)
                .addGap(18, 18, 18)
                .addComponent(showlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showlbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showlbl1)
                .addGap(53, 53, 53))
        );

        getContentPane().add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 760));

        orderproductpanel.setBackground(new java.awt.Color(43, 27, 61));
        orderproductpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(150, 150, 165));

        jButton1.setBackground(new java.awt.Color(150, 150, 165));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1076, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        orderproductpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 80));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Product Name ");
        orderproductpanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, 30));

        orderproductname.setBackground(new java.awt.Color(43, 27, 61));
        orderproductname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        orderproductname.setForeground(new java.awt.Color(255, 255, 255));
        orderproductname.setMaximumRowCount(100);
        orderproductpanel.add(orderproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 220, 30));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Quantity");
        orderproductpanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 30));

        orderquantity.setBackground(new java.awt.Color(43, 27, 61));
        orderquantity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        orderquantity.setForeground(new java.awt.Color(255, 255, 255));
        orderquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        orderproductpanel.add(orderquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 220, 30));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Dealer Name");
        orderproductpanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 110, 30));

        orderdealer.setBackground(new java.awt.Color(43, 27, 61));
        orderdealer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        orderdealer.setForeground(new java.awt.Color(255, 255, 255));
        orderdealer.setMaximumRowCount(100);
        orderproductpanel.add(orderdealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 220, 30));

        mytable.setBackground(new java.awt.Color(255, 255, 255));
        mytable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mytable.setForeground(new java.awt.Color(0, 0, 0));
        mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(mytable);

        orderproductpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 1010, 210));

        jButton9.setBackground(new java.awt.Color(43, 27, 61));
        jButton9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(71, 190, 85));
        jButton9.setText("Add");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 190, 85), 2));
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        orderproductpanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 90, 30));

        jButton10.setBackground(new java.awt.Color(43, 27, 61));
        jButton10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 204, 0));
        jButton10.setText("Clear");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        orderproductpanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 90, 30));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        orderproductpanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 40, 50));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        orderproductpanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 40, 50));

        newprodaddpanel.setBackground(new java.awt.Color(43, 27, 61));

        newdealeradd.setBackground(new java.awt.Color(43, 27, 61));
        newdealeradd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newdealeradd.setForeground(new java.awt.Color(255, 255, 255));
        newdealeradd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        newdealeradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newdealeraddActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(43, 27, 61));
        jButton11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(71, 190, 85));
        jButton11.setText("Add");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 190, 85), 2));
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(43, 27, 61));
        jButton12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(204, 204, 0));
        jButton12.setText("Clear");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(43, 27, 61));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Dealer Name");

        javax.swing.GroupLayout newprodaddpanelLayout = new javax.swing.GroupLayout(newprodaddpanel);
        newprodaddpanel.setLayout(newprodaddpanelLayout);
        newprodaddpanelLayout.setHorizontalGroup(
            newprodaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newprodaddpanelLayout.createSequentialGroup()
                .addGroup(newprodaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newprodaddpanelLayout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newprodaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newdealeradd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        newprodaddpanelLayout.setVerticalGroup(
            newprodaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newprodaddpanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newdealeradd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(newprodaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        orderproductpanel.add(newprodaddpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 250, 130));

        newprodaddpanel1.setBackground(new java.awt.Color(43, 27, 61));

        jLabel3.setBackground(new java.awt.Color(43, 27, 61));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Product Name");

        newprodadd.setBackground(new java.awt.Color(43, 27, 61));
        newprodadd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newprodadd.setForeground(new java.awt.Color(255, 255, 255));
        newprodadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        newprodadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newprodaddActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(43, 27, 61));
        jButton13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(71, 190, 85));
        jButton13.setText("Add");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 190, 85), 2));
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(43, 27, 61));
        jButton14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(204, 204, 0));
        jButton14.setText("Clear");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newprodaddpanel1Layout = new javax.swing.GroupLayout(newprodaddpanel1);
        newprodaddpanel1.setLayout(newprodaddpanel1Layout);
        newprodaddpanel1Layout.setHorizontalGroup(
            newprodaddpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newprodaddpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newprodaddpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newprodaddpanel1Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newprodaddpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newprodadd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        newprodaddpanel1Layout.setVerticalGroup(
            newprodaddpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newprodaddpanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newprodadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(newprodaddpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        orderproductpanel.add(newprodaddpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 250, 130));

        jButton7.setBackground(new java.awt.Color(43, 27, 61));
        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 0));
        jButton7.setText("Export");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        orderproductpanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 140, -1));

        getContentPane().add(orderproductpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1140, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addlogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlogolblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        PurchaseProducts ps = new PurchaseProducts();
        ps.setVisible(true);
    }//GEN-LAST:event_addlogolblMouseClicked

    private void addlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        PurchaseProducts ps = new PurchaseProducts();
        ps.setVisible(true);
    }//GEN-LAST:event_addlblMouseClicked

    private void selllogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selllogolblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SellProducts sp = new SellProducts();

        sp.setVisible(true);

    }//GEN-LAST:event_selllogolblMouseClicked

    private void sellblbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellblbMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SellProducts sp = new SellProducts();

        sp.setVisible(true);
    }//GEN-LAST:event_sellblbMouseClicked

    private void orderlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlogoMouseClicked
        // TODO add your handling code here:
       this.dispose();
        OrderProduct op = new OrderProduct();
        op.setVisible(true);
      

    }//GEN-LAST:event_orderlogoMouseClicked

    private void showlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlogoMouseClicked
        // TODO add your handling code here:
         this.dispose();
        ShowProducts ss = new ShowProducts();
        ss.setVisible(true);


    }//GEN-LAST:event_showlogoMouseClicked

    private void showlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ShowProducts ss = new ShowProducts();
        ss.setVisible(true);

    }//GEN-LAST:event_showlblMouseClicked

    private void showlbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlbl1MouseClicked
        // TODO add your handling code here:
        this.dispose();;
        Accounts a = new Accounts ();
        a.setVisible(true);
    }//GEN-LAST:event_showlbl1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");

            String product = orderproductname.getSelectedItem().toString();
            String qty = orderquantity.getText();
            String dealer = orderdealer.getSelectedItem().toString();
            java.util.Date date = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());

            String query = "insert into orderdata(product_name,quantity,destributor,date) values(?,?,?,?)";
            // String query2 = "insert into temp(p_name,p_qty,destributor,date) values(?,?,?,?)";
            PreparedStatement pst=Connect.con.prepareStatement(query);
            // PreparedStatement pst2=Connect.con.prepareStatement(query2);
            pst.setString(1, product);
            pst.setString(2, qty);
            pst.setString(3, dealer);
            pst.setDate(4, sqlDate);

            pst.executeUpdate();

            Connect.con.close();
            showtable();

            // Thank you for watching

        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        orderquantity.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        newprodaddpanel1.setVisible(true);
       
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        newprodaddpanel.setVisible(true);
      

    }//GEN-LAST:event_jLabel32MouseClicked

    private void newdealeraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newdealeraddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newdealeraddActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          String name = newdealeradd.getText();
        orderdealer.addItem(name);
        orderdealer.setSelectedItem(name);
        
       newprodaddpanel.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        newdealeradd.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void newprodaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newprodaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newprodaddActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         String name = newprodadd.getText();
        orderproductname.addItem(name);
        orderproductname.setSelectedItem(name);
        
        newprodaddpanel1.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        newprodadd.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            showtable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void orderlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        OrderProduct op = new OrderProduct();
        op.setVisible(true);
    }//GEN-LAST:event_orderlblMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();;
        Accounts a = new Accounts ();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        excelSheet();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addlbl;
    private javax.swing.JLabel addlogolbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menupanel;
    private javax.swing.JTable mytable;
    private javax.swing.JTextField newdealeradd;
    private javax.swing.JTextField newprodadd;
    private javax.swing.JPanel newprodaddpanel;
    private javax.swing.JPanel newprodaddpanel1;
    private javax.swing.JComboBox<String> orderdealer;
    private javax.swing.JLabel orderlbl;
    private javax.swing.JLabel orderlogo;
    private javax.swing.JComboBox<String> orderproductname;
    private javax.swing.JPanel orderproductpanel;
    private javax.swing.JTextField orderquantity;
    private javax.swing.JLabel sellblb;
    private javax.swing.JLabel selllogolbl;
    private javax.swing.JLabel showlbl;
    private javax.swing.JLabel showlbl1;
    private javax.swing.JLabel showlogo;
    // End of variables declaration//GEN-END:variables
}
