/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import classes.PurchaseProducts;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sakshi
 */
public class SellProducts extends javax.swing.JFrame {

    /**
     * Creates new form SellProducts
     */
    
    String tableClicked = "";
    
    public SellProducts() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        custaddpanel.setVisible(false);
           int initialDiscount = 0;
        String dis = Integer.toString(initialDiscount);
        
         discountinpertxt.setText(dis);
        discountinamttxt.setText(dis);
       
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     @SuppressWarnings("unchecked")
     
     
     //get bill number
        public int generatebillno(){
        int bill = 0;
        try {
            
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            String query ="select distinct max(billno) from sellproducts";
            ResultSet rs = Connect.st.executeQuery(query);
            
            while (rs.next()) {
                bill = rs.getInt(1);
                
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
        
        return ++bill;
    }
        
         public int generateBillForDescounts(){
        int bill = 0;
        try {
            
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            String query ="select distinct max(billno) from perdiscount";
            ResultSet rs = Connect.st.executeQuery(query);
            
            while (rs.next()) {
                bill = rs.getInt(1);
                
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
        
        return ++bill;
    }
     
    
     
     
   
     //show product on add product panell
    public  void showProductsOnAddPanel() {

        try {

            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            String query = "select distinct product_name from products";
            ResultSet rs = Connect.st.executeQuery(query);
            while (rs.next()) {
                String prod = rs.getString("product_name");
                productnameonsell.addItem(prod);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }
    
     //show customers on sell product panel
     
     public void showCustomerOnSellPAnel() {

        try {

            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            String query = "select distinct customer_name from sellproducts";
            ResultSet rs = Connect.st.executeQuery(query);
            while (rs.next()) {
                String customer = rs.getString("customer_name");
                newcusttxt.addItem(customer);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }
     
     //show customer contact number on sell panel.
      public void showCustContactOnSellPanel(){
           try {
            String name = newcusttxt.getSelectedItem().toString();
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            String query ="select cust_contact_no from sellproducts where customer_name='" + name + "'";
            ResultSet rs = Connect.st.executeQuery(query);
            while (rs.next()) {
                String contNo = rs.getString(1);
                custcontacttxt.setText(contNo);
                
              
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
          
      }
      
      //show hsn number on sell panel
      public void shopwHSNOnSellPanel() {
        try {
            String name = productnameonsell.getSelectedItem().toString();
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            String query ="select hsn_number from products where product_name='" + name + "'";
            ResultSet rs = Connect.st.executeQuery(query);
            while (rs.next()) {
                String hsn = rs.getString(1);
                hsnnolbl.setText(hsn);
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }
      
       //show sgst in sell product panel
      public void showSGstOnSellPanel() {

        try {
            String name = productnameonsell.getSelectedItem().toString();
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            String query = "select sgst,cgst from products where product_name='" + name + "'";
            ResultSet rs = Connect.st.executeQuery(query);
            while (rs.next()) {
                String sgst = Float.toString(rs.getFloat(1));
                String cgst = Float.toString(rs.getFloat(2));
                sellcgsttxt.setText(cgst);
                sellsgsttxt.setText(sgst);
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

    }
      
       // show sell products table on sell panel
      void showSellProductsOnSellPanel() throws ClassNotFoundException {

        String sql = "select id as SR, product_name as Product, quantity as Quantity, mrp as MRP, total_mrp_of_prod as Total, sgst as SGST, cgst as CGST, total_price_scgst as GrandTotal from tempselldata";
        try {

            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"","");
            Connect.st = Connect.con.createStatement();
            ResultSet rs = Connect.st.executeQuery(sql);
            selldatatable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "No record in this table");

        }
    }
    
         //sgow grand total in sell panel
       public void showGrandTotalInSellPanel() {
        try {
            //String name = productnameonsell.getSelectedItem().toString();
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();
            String query = "select sum(total_price_scgst) from tempselldata";
            ResultSet rs = Connect.st.executeQuery(query);
            while (rs.next()) {
                String price = Float.toString(rs.getFloat(1));
                sellgrandtotaltxt.setText(price);
                finalamount.setText(price);
                //finalgtotal.setText(price);
                   
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }
       
        //show mrp method
    public void showMrpOnSellPanel() {
        try {
            String name = productnameonsell.getSelectedItem().toString();
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();
            String query = "select (mrp)max from products where product_name='" + name + "'";
            ResultSet rs = Connect.st.executeQuery(query);
            while (rs.next()) {
                String price = Double.toString(rs.getDouble(1));
                mrptxtsell.setText(price);
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }
      
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menupanel = new javax.swing.JPanel();
        addlogolbl = new javax.swing.JLabel();
        addlbl = new javax.swing.JLabel();
        selllogolbl = new javax.swing.JLabel();
        sellblb = new javax.swing.JLabel();
        orderlogo = new javax.swing.JLabel();
        orderlbl = new javax.swing.JLabel();
        showlogo = new javax.swing.JLabel();
        showlbl = new javax.swing.JLabel();
        showlbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sellproductpanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        newcusttxt = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        hsnnolbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sellquantity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        custaddpanel = new javax.swing.JPanel();
        newproductlbl = new javax.swing.JLabel();
        addcusttxt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        mrptxtsell = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        custcontacttxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sellsgsttxt = new javax.swing.JTextField();
        sellcgsttxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        sellgrandtotaltxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selldatatable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        discountpanel = new javax.swing.JPanel();
        finalamount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        discountinpertxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        discountinamttxt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        finalgtotal = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        productnameonsell = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setBackground(new java.awt.Color(150, 150, 165));

        addlogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addlogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlogolblMouseClicked(evt);
            }
        });

        addlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addlbl.setForeground(new java.awt.Color(0, 0, 0));
        addlbl.setText("   Add");
        addlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlblMouseClicked(evt);
            }
        });

        selllogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart-of-checkered-design.png"))); // NOI18N
        selllogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selllogolblMouseClicked(evt);
            }
        });

        sellblb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sellblb.setForeground(new java.awt.Color(0, 0, 0));
        sellblb.setText("    Sell");
        sellblb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellblbMouseClicked(evt);
            }
        });

        orderlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bag.png"))); // NOI18N
        orderlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlogoMouseClicked(evt);
            }
        });

        orderlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderlbl.setForeground(new java.awt.Color(0, 0, 0));
        orderlbl.setText(" Order");
        orderlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlblMouseClicked(evt);
            }
        });

        showlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        showlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlogoMouseClicked(evt);
            }
        });

        showlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl.setForeground(new java.awt.Color(0, 0, 0));
        showlbl.setText("  Shwo");
        showlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlblMouseClicked(evt);
            }
        });

        showlbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl1.setForeground(new java.awt.Color(0, 0, 0));
        showlbl1.setText(" Account");
        showlbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlbl1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addlogolbl)
                        .addComponent(orderlogo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(addlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellblb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selllogolbl)
                        .addComponent(orderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showlogo)
                        .addComponent(showlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(showlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(addlogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addlbl)
                .addGap(18, 18, 18)
                .addComponent(selllogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellblb)
                .addGap(18, 18, 18)
                .addComponent(orderlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderlbl)
                .addGap(18, 18, 18)
                .addComponent(showlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showlbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showlbl1)
                .addGap(53, 53, 53))
        );

        getContentPane().add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 760));

        sellproductpanel.setBackground(new java.awt.Color(43, 27, 61));
        sellproductpanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sellproductpanelPropertyChange(evt);
            }
        });
        sellproductpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(150, 150, 165));

        jButton9.setBackground(new java.awt.Color(150, 150, 165));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(1077, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        sellproductpanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 80));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Product Name ");
        sellproductpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, 20));

        newcusttxt.setBackground(new java.awt.Color(43, 27, 61));
        newcusttxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newcusttxt.setForeground(new java.awt.Color(255, 255, 255));
        newcusttxt.setMaximumRowCount(100);
        newcusttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        newcusttxt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                newcusttxtItemStateChanged(evt);
            }
        });
        sellproductpanel.add(newcusttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 220, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("HSN No.");
        sellproductpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        hsnnolbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        hsnnolbl.setForeground(new java.awt.Color(255, 255, 255));
        hsnnolbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sellproductpanel.add(hsnnolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 220, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Quantity");
        sellproductpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        sellquantity.setBackground(new java.awt.Color(43, 27, 61));
        sellquantity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sellquantity.setForeground(new java.awt.Color(255, 255, 255));
        sellquantity.setToolTipText("please enter quantity.");
        sellquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sellproductpanel.add(sellquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 220, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Grand Total");
        sellproductpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 110, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MRP");
        sellproductpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 110, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        sellproductpanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 40, 50));

        custaddpanel.setBackground(new java.awt.Color(43, 27, 61));

        newproductlbl.setVisible(false);
        newproductlbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newproductlbl.setForeground(new java.awt.Color(255, 255, 255));
        newproductlbl.setText("Add new customer");

        addcusttxt.setBackground(new java.awt.Color(43, 27, 61));
        addcusttxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addcusttxt.setForeground(new java.awt.Color(255, 255, 255));
        addcusttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton6.setBackground(new java.awt.Color(43, 27, 61));
        jButton6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 0));
        jButton6.setText("Add");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(43, 27, 61));
        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 0));
        jButton7.setText("Clear");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout custaddpanelLayout = new javax.swing.GroupLayout(custaddpanel);
        custaddpanel.setLayout(custaddpanelLayout);
        custaddpanelLayout.setHorizontalGroup(
            custaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custaddpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(custaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newproductlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(custaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(custaddpanelLayout.createSequentialGroup()
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addcusttxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        custaddpanelLayout.setVerticalGroup(
            custaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custaddpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newproductlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addcusttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(custaddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sellproductpanel.add(custaddpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 250, 140));

        mrptxtsell.setBackground(new java.awt.Color(43, 27, 61));
        mrptxtsell.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mrptxtsell.setForeground(new java.awt.Color(255, 255, 255));
        mrptxtsell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sellproductpanel.add(mrptxtsell, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Customer name");
        sellproductpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, 20));

        custcontacttxt.setBackground(new java.awt.Color(43, 27, 61));
        custcontacttxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        custcontacttxt.setForeground(new java.awt.Color(255, 255, 255));
        custcontacttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sellproductpanel.add(custcontacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 220, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Customer contact No.");
        sellproductpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 180, 20));

        sellsgsttxt.setBackground(new java.awt.Color(43, 27, 61));
        sellsgsttxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sellsgsttxt.setForeground(new java.awt.Color(255, 255, 255));
        sellsgsttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellsgsttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sellproductpanel.add(sellsgsttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 220, 30));

        sellcgsttxt.setBackground(new java.awt.Color(43, 27, 61));
        sellcgsttxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sellcgsttxt.setForeground(new java.awt.Color(255, 255, 255));
        sellcgsttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellcgsttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sellproductpanel.add(sellcgsttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 220, 30));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("SGST");
        sellproductpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 70, 20));

        sellgrandtotaltxt.setBackground(new java.awt.Color(43, 27, 61));
        sellgrandtotaltxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sellgrandtotaltxt.setForeground(new java.awt.Color(255, 255, 255));
        sellgrandtotaltxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellgrandtotaltxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sellproductpanel.add(sellgrandtotaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 220, 30));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CGST");
        sellproductpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 70, 20));

        selldatatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "HSN", "Quantity", "MRP", "Total", "SGST", "SGSTAmt", "CGST", "CGSTAmt", "GrandTotal"
            }
        ));
        selldatatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selldatatableMouseClicked(evt);
            }
        });
        selldatatable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                selldatatableInputMethodTextChanged(evt);
            }
        });
        selldatatable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selldatatablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(selldatatable);

        sellproductpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 930, 130));

        jButton1.setBackground(new java.awt.Color(43, 27, 61));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Delete");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sellproductpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 80, 30));

        jButton2.setBackground(new java.awt.Color(43, 27, 61));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setText("Place Oder");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        sellproductpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 110, 30));

        discountpanel.setBackground(new java.awt.Color(43, 27, 61));
        discountpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        finalamount.setBackground(new java.awt.Color(43, 27, 61));
        finalamount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        finalamount.setForeground(new java.awt.Color(255, 255, 255));
        finalamount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        finalamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Grand Total");

        discountinpertxt.setBackground(new java.awt.Color(43, 27, 61));
        discountinpertxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        discountinpertxt.setForeground(new java.awt.Color(255, 255, 255));
        discountinpertxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        discountinpertxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Discount in amount");

        discountinamttxt.setBackground(new java.awt.Color(43, 27, 61));
        discountinamttxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        discountinamttxt.setForeground(new java.awt.Color(255, 255, 255));
        discountinamttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        discountinamttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        discountinamttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountinamttxtActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Discount %");

        jButton4.setBackground(new java.awt.Color(43, 27, 61));
        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 0));
        jButton4.setText("Apply");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        finalgtotal.setBackground(new java.awt.Color(43, 27, 61));
        finalgtotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        finalgtotal.setForeground(new java.awt.Color(255, 255, 255));
        finalgtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        finalgtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        finalgtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalgtotalActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Final Grand Total");

        jButton5.setBackground(new java.awt.Color(43, 27, 61));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 0));
        jButton5.setText("Apply");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(43, 27, 61));
        jButton8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 153, 0));
        jButton8.setText("Print");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout discountpanelLayout = new javax.swing.GroupLayout(discountpanel);
        discountpanel.setLayout(discountpanelLayout);
        discountpanelLayout.setHorizontalGroup(
            discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(discountpanelLayout.createSequentialGroup()
                        .addComponent(discountinpertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(discountpanelLayout.createSequentialGroup()
                        .addComponent(discountinamttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalgtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        discountpanelLayout.setVerticalGroup(
            discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountpanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountinpertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountinamttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finalgtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        sellproductpanel.add(discountpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 340, 370));

        productnameonsell.setBackground(new java.awt.Color(43, 27, 61));
        productnameonsell.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        productnameonsell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        productnameonsell.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productnameonsellItemStateChanged(evt);
            }
        });
        sellproductpanel.add(productnameonsell, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, 30));

        jButton10.setBackground(new java.awt.Color(43, 27, 61));
        jButton10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 153, 0));
        jButton10.setText("Add");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        sellproductpanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 70, 30));

        getContentPane().add(sellproductpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1110, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addlogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlogolblMouseClicked
        // TODO add your handling code here:
           this.dispose();
        PurchaseProducts pp = new PurchaseProducts();
        pp.setVisible(true);

    }//GEN-LAST:event_addlogolblMouseClicked

    private void addlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlblMouseClicked
        // TODO add your handling code here:
          this.dispose();
        PurchaseProducts pp = new PurchaseProducts();
        pp.setVisible(true);
      
    }//GEN-LAST:event_addlblMouseClicked

    private void selllogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selllogolblMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_selllogolblMouseClicked

    private void sellblbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellblbMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_sellblbMouseClicked

    private void orderlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlogoMouseClicked
        // TODO add your handling code here:
        this.dispose();
          OrderProduct op = new OrderProduct();
        op.setVisible(true);

    }//GEN-LAST:event_orderlogoMouseClicked

    private void showlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlogoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ShowProducts ss = new ShowProducts();
        ss.setVisible(true);

    }//GEN-LAST:event_showlogoMouseClicked

    private void showlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ShowProducts ss = new ShowProducts();
        ss.setVisible(true);


    }//GEN-LAST:event_showlblMouseClicked

    private void showlbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlbl1MouseClicked
        // TODO add your handling code here:
        this.dispose();;
        Accounts a = new Accounts ();
        a.setVisible(true);
    }//GEN-LAST:event_showlbl1MouseClicked

    private void newcusttxtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_newcusttxtItemStateChanged
    showCustContactOnSellPanel();
        
    }//GEN-LAST:event_newcusttxtItemStateChanged

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
custaddpanel.setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        String newCust = addcusttxt.getText();
        newcusttxt.addItem(newCust);
        newcusttxt.setSelectedItem(newCust);

        custaddpanel.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void selldatatableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selldatatableMouseClicked
        // TODO add your handling code here:
        try{
            int row = selldatatable.getSelectedRow();
            tableClicked = (selldatatable.getModel().getValueAt(row, 0).toString());

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_selldatatableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           int i = selldatatable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)selldatatable.getModel();
        
        if(i>=0){
        
           NumberFormat nf = NumberFormat.getInstance();
     
          int row = selldatatable.getSelectedRow();
         
          try{
        double value = nf.parse(selldatatable.getModel().getValueAt(row, 9).toString()).doubleValue();
              System.out.println(value);
              
              String gValue = sellgrandtotaltxt.getText();
              double GValue = Double.parseDouble(gValue);
              
              double res = GValue - value ; 
              System.out.println(res);
              
              String REs = Double.toString(res);
              sellgrandtotaltxt.setText(REs);
               finalamount.setText(REs);
              model.removeRow(row);
        
          }catch(Exception e){
              
          }
         
          
       
        }
       
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     try{
         
          int rows = selldatatable.getRowCount();
          int billNo = generatebillno();
          
          for(int row = 0; row<rows; row++)
         { 
           Class.forName(Connect.myDriver);
           Connect.con = DriverManager.getConnection(Connect.url,"","");
           PreparedStatement pst = null;
            PreparedStatement pst1 = null;
             PreparedStatement pst2 = null;
           
           String product = (String)selldatatable.getValueAt(row, 0);
           String hsn = (String)selldatatable.getValueAt(row, 1);
           String qty = (String)selldatatable.getValueAt(row, 2);
           String Mrp = (String)selldatatable.getValueAt(row, 3);
           
           String cust_name = newcusttxt.getSelectedItem().toString();
           String cust_contact = custcontacttxt.getText();
           
           String productTotalAmt = (String)selldatatable.getValueAt(row, 4);
           String Sgst = (String)selldatatable.getValueAt(row, 5);
           String sgstAmount = (String)selldatatable.getValueAt(row, 6);
           
            String Cgst = (String)selldatatable.getValueAt(row, 7);
            String cgstAmount = (String)selldatatable.getValueAt(row, 8);
           
            String grand_total =  (String)selldatatable.getValueAt(row, 9);
            
            String bill = Integer.toString(billNo);
            
          
           java.util.Date date = new java.util.Date();
           java.sql.Date sqlDate = new java.sql.Date(date.getTime());
           java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
           
           
           String insertSellData = "insert into sellproducts(product_name, hsn_number, quantity, mrp, total_mrp_of_prod, customer_name, cust_contact_no, sgst, cgst, sgstamt, cgstamt, total_price_scgst, billno, date, time )values('"+product+"', "+hsn+", "+qty+", "+Mrp+", "+productTotalAmt+", '"+cust_name+"', "+cust_contact+", "+Sgst+", "+Cgst+", "+sgstAmount+", "+cgstAmount+", "+grand_total+", "+bill+", '"+sqlDate+"', '"+sqlTime+"')";
           
           
             String insertTempSellData = "insert into tempselldata(product_name, hsn_number, quantity, mrp, total_mrp_of_prod, customer_name, cust_contact_no, sgst, cgst, sgstamt, cgstamt, total_price_scgst, billno, date, time)values('"+product+"', "+hsn+", "+qty+", "+Mrp+", "+productTotalAmt+", '"+cust_name+"', "+cust_contact+", "+Sgst+", "+Cgst+", "+sgstAmount+", "+cgstAmount+", "+grand_total+", "+bill+", '"+sqlDate+"', '"+sqlTime+"')";
           
             String query3 = "update available set quantity = quantity-" + qty + " where product_name='" + product + "'";
           
           
            pst = Connect.con.prepareStatement(insertSellData);
             pst1 = Connect.con.prepareStatement(insertTempSellData);
                pst2 = Connect.con.prepareStatement(query3);
     
            pst.execute();     
              pst1.execute();
               pst2.execute();
                
         }
            JOptionPane.showMessageDialog(null, "Successfully Save");
     }catch(Exception e){
           JOptionPane.showMessageDialog(this,e.getMessage());
     }
     
       DefaultTableModel model = (DefaultTableModel) selldatatable.getModel();
        model.setRowCount(0);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void discountinamttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountinamttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountinamttxtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String finalTotal =  finalamount.getText();
        float finalAmount = Float.parseFloat(finalTotal);

        String dis = discountinpertxt.getText();
        float discount = Float.parseFloat(dis);

        float discountAmount = (finalAmount /100) * discount;

        String a = Float.toString(discountAmount);
        discountinamttxt.setText(a);

        String finalAmountWithDiscount =Float.toString(finalAmount - discountAmount)  ;
        finalgtotal.setText(finalAmountWithDiscount);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void finalgtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalgtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalgtotalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String finalTotal =  finalamount.getText();
        float finalAmount = Float.parseFloat(finalTotal);

        String disAmount = discountinamttxt.getText();
        float DisAmount = Float.parseFloat(disAmount);

        //  String discountInPer = Float.toString((DisAmount * 100) / finalAmount) ;

        float discountInPer = (DisAmount * 100) / finalAmount ;

        String finalDiscountPrice =Float.toString(finalAmount - DisAmount) ;

        float roundValue = Math.round(discountInPer);

        String rvalueInStr = Float.toString(roundValue);

        discountinpertxt.setText(rvalueInStr);

        finalgtotal.setText(finalDiscountPrice);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         //insert final amount with discount in discounts table.
     
            try{
           String myDriver = "com.mysql.jdbc.Driver";
           String url = "jdbc:mysql://localhost:3306/msystem?autoReconnect=true&useSSL=false";
           Class.forName(myDriver);
            Connection con = DriverManager.getConnection(url,"","");
            Statement st1 = con.createStatement();
            Statement st2 = con.createStatement();
            
            
             java.util.Date date = new java.util.Date();
             java.sql.Date sqlDate = new java.sql.Date(date.getTime());
             java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
            
             String prod_name =  productnameonsell.getSelectedItem().toString();
           
             int billNo = generateBillForDescounts();
            
            float fAmount = Float.parseFloat(finalamount.getText());
            float disPer = Float.parseFloat(discountinpertxt.getText());
            float disAmt = Float.parseFloat(discountinamttxt.getText());
            float fAmt = Float.parseFloat(finalgtotal.getText());
            
            String qr = "insert into tempdiscounts(billno,product_name,total, discount_in_per, discount_in_amt, final_grand_total, date, time)values("+billNo+" ,'"+prod_name+"', "+fAmount+", "+disPer+", "+disAmt+", "+fAmt+",  '"+sqlDate+"',  '"+sqlTime+"')";
             String qr1 = "insert into perdiscount(billno,product_name,total, discount_in_per, discount_in_amt, final_grand_total, date, time)values("+billNo+" ,'"+prod_name+"', "+fAmount+", "+disPer+", "+disAmt+", "+fAmt+", '"+sqlDate+"',  '"+sqlTime+"')";
              st1.executeUpdate(qr);
                 st2.executeUpdate(qr1);
                con.close();
                
               
                
//                 // Construct data
			String apiKey = "apikey=" + "qmxY7WMFOq4-Tsyytw2C1Q5AMSazK9h8HIsOPtKTXJ";
                         String cname = newcusttxt.getSelectedItem().toString();
                         System.out.println(cname);
                         
                         String custno = custcontacttxt.getText();
                       System.out.println(custno);
                       
			String message = "&message=" + "Hey,"+cname+"\nThank you for visiting CodeWind.\nYour bill amount is:"+fAmt+"\nHave a good day.";
			String sender = "&sender=" +"TXTLCL";
			String numbers = "&numbers=" + custcontacttxt.getText();
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) {
				//stringBuffer.append(line);
                                JOptionPane.showMessageDialog(rootPane, "message"+line);
			}
			rd.close();
			
			//return stringBuffer.toString();
                
                
                
                
           }catch(Exception e){
               
           }
            
        
            
    
        BillGenerate b = new BillGenerate();
        b.setVisible(true);
      
       

    }//GEN-LAST:event_jButton8ActionPerformed

    private void sellproductpanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sellproductpanelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sellproductpanelPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        newproductlbl.setVisible(true);
              showProductsOnAddPanel();
              showCustomerOnSellPAnel();
            
            
       
    }//GEN-LAST:event_formWindowOpened

    private void orderlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlblMouseClicked
        // TODO add your handling code here:
        this.dispose();
          OrderProduct op = new OrderProduct();
        op.setVisible(true);
    }//GEN-LAST:event_orderlblMouseClicked

    private void productnameonsellItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productnameonsellItemStateChanged
        // TODO add your handling code here:
        showMrpOnSellPanel();
        showSGstOnSellPanel();
        shopwHSNOnSellPanel();
    }//GEN-LAST:event_productnameonsellItemStateChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();;
        Accounts a = new Accounts ();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel dm = (DefaultTableModel)selldatatable.getModel();
          
          String qty = sellquantity.getText();
          float productQuantity = Float.parseFloat(qty);
          
          String mrp = mrptxtsell.getText();
          float pmrp = Float.parseFloat(mrp);
          
          float total = productQuantity * pmrp;
          String PTotal = Float.toString(pmrp);
          
          
          String sGST = sellsgsttxt.getText();
          float SGST = Float.parseFloat(sGST);
          
          //sgst amount calculation
          float sgst_amt = (total * SGST) / 100;
          String sgstamt = Float.toString(sgst_amt);
          
          String cGST = sellcgsttxt.getText();
          float CGST = Float.parseFloat(cGST);
          
           //cgst amount calculation
          float cgst_amt = (total * CGST) / 100;
          String cgstamt = Float.toString(cgst_amt);
          
           //calculation of total price with sgst and cgst on total product price.
          float productPriceSCGST = total + sgst_amt + cgst_amt;
          String grandTotal = Float.toString(productPriceSCGST);
          
          
          dm.addRow(new Object[]{productnameonsell.getSelectedItem().toString(), hsnnolbl.getText(), qty,
                     mrp,PTotal,sGST,sgstamt,cGST,cgstamt,grandTotal});
     
         double sum = 0;
        for(int i = 0; i < selldatatable.getRowCount(); i++)
        {
            NumberFormat nf = NumberFormat.getInstance();
     
              try {
                  double a = nf.parse(selldatatable.getValueAt(i, 9).toString()).doubleValue();
                  sum = sum + a;
              } catch (ParseException ex) {
                
              }
            
            System.out.println(sum);
        }
        
        sellgrandtotaltxt.setText(Double.toString(sum));
           finalamount.setText(Double.toString(sum));
           
           sellquantity.setText("");
          
    }//GEN-LAST:event_jButton10ActionPerformed

    private void selldatatableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_selldatatableInputMethodTextChanged
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_selldatatableInputMethodTextChanged

    private void selldatatablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selldatatablePropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_selldatatablePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addcusttxt;
    private javax.swing.JLabel addlbl;
    private javax.swing.JLabel addlogolbl;
    private javax.swing.JPanel custaddpanel;
    public static javax.swing.JTextField custcontacttxt;
    private javax.swing.JTextField discountinamttxt;
    private javax.swing.JTextField discountinpertxt;
    private javax.swing.JPanel discountpanel;
    private javax.swing.JTextField finalamount;
    private javax.swing.JTextField finalgtotal;
    private javax.swing.JLabel hsnnolbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menupanel;
    private javax.swing.JTextField mrptxtsell;
    private javax.swing.JComboBox<String> newcusttxt;
    private javax.swing.JLabel newproductlbl;
    private javax.swing.JLabel orderlbl;
    private javax.swing.JLabel orderlogo;
    private javax.swing.JComboBox<String> productnameonsell;
    private javax.swing.JLabel sellblb;
    private javax.swing.JTextField sellcgsttxt;
    private javax.swing.JTable selldatatable;
    private javax.swing.JTextField sellgrandtotaltxt;
    private javax.swing.JLabel selllogolbl;
    private javax.swing.JPanel sellproductpanel;
    private javax.swing.JTextField sellquantity;
    private javax.swing.JTextField sellsgsttxt;
    private javax.swing.JLabel showlbl;
    private javax.swing.JLabel showlbl1;
    private javax.swing.JLabel showlogo;
    // End of variables declaration//GEN-END:variables
}
