/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;


import java.awt.Toolkit;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Sakshi
 */
public class ShowProducts extends javax.swing.JFrame {

    /**
     * Creates new form ShowProducts
     */
    public ShowProducts() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        panel_dealer.setVisible(false);
        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void excelSheet(){
          FileOutputStream fos = null;
          BufferedOutputStream bos = null;
          XSSFWorkbook excelJTableExporter = null;
        
        JFileChooser jfc = new JFileChooser("C:\\Users\\Sakshi\\Desktop");
        jfc.setDialogTitle("Save As");
        
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls");
        jfc.setFileFilter(fnef);
        int excelChooser =  jfc.showSaveDialog(null);
      
        
      
     
        
                
        if(excelChooser == JFileChooser.APPROVE_OPTION){
       
            try {
                excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable sheet");
                for(int i = 0 ; i < availableqtydatatable.getRowCount() ; i++){
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for(int j = 0 ; j <  availableqtydatatable.getColumnCount() ; j++){
                        XSSFCell excelCell = excelRow.createCell(j);
                        
                         
                        excelCell.setCellValue(availableqtydatatable.getValueAt(i, j).toString());
                      
                    }
                    
                }     fos = new FileOutputStream(jfc.getSelectedFile() + ".xls");
                 bos = new BufferedOutputStream(fos);
                excelJTableExporter.write(bos);
                JOptionPane.showMessageDialog(null, "Exported successfully...");
            } catch (FileNotFoundException ex) {
               ex.printStackTrace();
            }  catch (IOException ex) {
                   ex.printStackTrace();
               } finally {
                try {
                      if(bos != null){
                           bos.close();
                    }
                    if(fos != null){
                           fos.close();
                    }
                  
                     if(excelJTableExporter != null){
                           excelJTableExporter.close();
                    }
                 
                } catch (IOException ex) {
                   ex.printStackTrace();
                }
            }
          
          
          
          
      }
    }
    
    
    void showSellProducts(){
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String start_date = d.format(billsdate.getDate());
        String end_date = d.format(billndate.getDate());
     
        
        String query_show_product_details = "SELECT  billno as Bill, product_name as Product, hsn_number as HSN, quantity as Quantity, mrp as MRP, total_mrp_of_prod as TotalMrp, sgst as SGST, sgstamt as SGSTAmt, cgst as CGST, cgstamt as CGSTAmt, total_price_scgst as GrandTotal,customer_name as Customer, cust_contact_no as ContactNo, date as Date, time as Time  FROM `sellproducts` WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'";
        try{
            Class.forName(Connect.myDriver);
            Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();

            ResultSet rs = Connect.st.executeQuery(query_show_product_details);

            availableqtydatatable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(ClassNotFoundException | SQLException e){
             JOptionPane.showMessageDialog(null, "No record in this table"); 
        }
        
    }
    
              
              
              
              
    
      void showDealers(){
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String start_date = d.format(DayDealStart.getDate());
        String end_date = d.format(DaySealEnd.getDate());
        String name = cmDeal.getSelectedItem().toString();
        
        String query_show_product_details = "SELECT product_name as Product, hsn_number as HSN, quantity as Quantity, product_price as ProductPrice, mrp as MRP, mrp_total_price as Total_MRP, sgst as SGST, cgst as CGST, Bill_no as Bill, External_invoice as Invoice, destributor as Dealer FROM `products` WHERE date BETWEEN '"+start_date+"' AND '"+end_date+"'  AND destributor='"+name+"'";
        try{
                Class.forName(Connect.myDriver);
                Connect.con = DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
                Connect.st = Connect.con.createStatement();
                
                ResultSet rs = Connect.st.executeQuery(query_show_product_details);
                
                availableqtydatatable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(ClassNotFoundException | SQLException e){
                System.out.println(e);
            }
        
    }
      
      
      public void showdealers(){
            
            try{
                
                Class.forName(Connect.myDriver);
                Connect.con =DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
                Connect.st = Connect.con.createStatement();
                String query = "select distinct destributor from products";
                ResultSet rs = Connect.st.executeQuery(query);
                while(rs.next()){
                    String dealer = rs.getString("destributor");
                    cmDeal.addItem(dealer);
                }
                
            }
            catch(Exception e){
                System.out.println(e);
            }
            
            
            
        }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableqtydatatable = new javax.swing.JTable();
        panel_dealer = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cmDeal = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        DaySealEnd = new com.toedter.calendar.JDateChooser();
        DayDealStart = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        searchboxtxt = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        billsdate = new com.toedter.calendar.JDateChooser();
        billndate = new com.toedter.calendar.JDateChooser();
        jButton8 = new javax.swing.JButton();
        menupanel = new javax.swing.JPanel();
        addlogolbl = new javax.swing.JLabel();
        addlbl = new javax.swing.JLabel();
        selllogolbl = new javax.swing.JLabel();
        sellblb = new javax.swing.JLabel();
        orderlogo = new javax.swing.JLabel();
        orderlbl = new javax.swing.JLabel();
        showlogo = new javax.swing.JLabel();
        showlbl = new javax.swing.JLabel();
        showlbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 27, 61));

        jPanel2.setBackground(new java.awt.Color(150, 150, 165));

        jButton3.setBackground(new java.awt.Color(150, 150, 165));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(43, 27, 61));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Available Products");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        availableqtydatatable.setBackground(new java.awt.Color(255, 255, 255));
        availableqtydatatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(availableqtydatatable);

        panel_dealer.setBackground(new java.awt.Color(43, 27, 61));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Dealer Name");

        cmDeal.setBackground(new java.awt.Color(43, 27, 61));
        cmDeal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmDeal.setForeground(new java.awt.Color(255, 255, 255));
        cmDeal.setMaximumRowCount(100);
        cmDeal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmDealItemStateChanged(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Starting Date");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Ending Date");

        DaySealEnd.setBackground(new java.awt.Color(43, 27, 61));
        DaySealEnd.setDateFormatString("yyyy-MM-dd");

        DayDealStart.setBackground(new java.awt.Color(43, 27, 61));
        DayDealStart.setDateFormatString("yyyy-MM-dd");

        jButton6.setBackground(new java.awt.Color(43, 27, 61));
        jButton6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 0));
        jButton6.setText("Show");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dealerLayout = new javax.swing.GroupLayout(panel_dealer);
        panel_dealer.setLayout(panel_dealerLayout);
        panel_dealerLayout.setHorizontalGroup(
            panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dealerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DayDealStart, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(cmDeal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DaySealEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dealerLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        panel_dealerLayout.setVerticalGroup(
            panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dealerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmDeal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DayDealStart, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_dealerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DaySealEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(43, 27, 61));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 0));
        jButton2.setText("Dealers Data");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 2));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        searchboxtxt.setBackground(new java.awt.Color(43, 27, 61));
        searchboxtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        searchboxtxt.setForeground(new java.awt.Color(255, 255, 255));
        searchboxtxt.setText("Search here");
        searchboxtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        searchboxtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchboxtxtMouseClicked(evt);
            }
        });
        searchboxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxtxtActionPerformed(evt);
            }
        });
        searchboxtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxtxtKeyReleased(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(43, 27, 61));
        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 0));
        jButton7.setText("Export");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(43, 27, 61));
        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 0));
        jButton4.setText("Customers bill");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(43, 27, 61));

        jButton5.setBackground(new java.awt.Color(43, 27, 61));
        jButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 0));
        jButton5.setText("Show");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Starting Date");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ending Date");

        billsdate.setBackground(new java.awt.Color(43, 27, 61));

        billndate.setBackground(new java.awt.Color(43, 27, 61));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(billsdate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(billndate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(billsdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billndate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(26, 26, 26))
        );

        jButton8.setBackground(new java.awt.Color(43, 27, 61));
        jButton8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 153, 0));
        jButton8.setText("Print Bill");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchboxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_dealer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_dealer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchboxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1110, 760));

        menupanel.setBackground(new java.awt.Color(150, 150, 165));

        addlogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addlogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlogolblMouseClicked(evt);
            }
        });

        addlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addlbl.setForeground(new java.awt.Color(0, 0, 0));
        addlbl.setText("   Add");
        addlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlblMouseClicked(evt);
            }
        });

        selllogolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart-of-checkered-design.png"))); // NOI18N
        selllogolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selllogolblMouseClicked(evt);
            }
        });

        sellblb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sellblb.setForeground(new java.awt.Color(0, 0, 0));
        sellblb.setText("    Sell");
        sellblb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellblbMouseClicked(evt);
            }
        });

        orderlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bag.png"))); // NOI18N
        orderlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlogoMouseClicked(evt);
            }
        });

        orderlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderlbl.setForeground(new java.awt.Color(0, 0, 0));
        orderlbl.setText(" Order");
        orderlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderlblMouseClicked(evt);
            }
        });

        showlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        showlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlogoMouseClicked(evt);
            }
        });

        showlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl.setForeground(new java.awt.Color(0, 0, 0));
        showlbl.setText("  Shwo");
        showlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlblMouseClicked(evt);
            }
        });

        showlbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        showlbl1.setForeground(new java.awt.Color(0, 0, 0));
        showlbl1.setText(" Account");
        showlbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showlbl1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addlogolbl)
                        .addComponent(orderlogo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(addlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellblb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selllogolbl)
                        .addComponent(orderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showlogo)
                        .addComponent(showlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(addlogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addlbl)
                .addGap(12, 12, 12)
                .addComponent(selllogolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellblb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showlbl1)
                .addGap(96, 96, 96))
        );

        getContentPane().add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addlogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlogolblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        PurchaseProducts ps = new PurchaseProducts();
        ps.setVisible(true);
    }//GEN-LAST:event_addlogolblMouseClicked

    private void addlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlblMouseClicked

    private void selllogolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selllogolblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SellProducts sp = new SellProducts();

        sp.setVisible(true);
    }//GEN-LAST:event_selllogolblMouseClicked

    private void sellblbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellblbMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SellProducts sp = new SellProducts();

        sp.setVisible(true);
    }//GEN-LAST:event_sellblbMouseClicked

    private void orderlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlogoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        OrderProduct os = new OrderProduct();
        os.setVisible(true);

    }//GEN-LAST:event_orderlogoMouseClicked

    private void showlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showlogoMouseClicked

    private void showlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showlblMouseClicked

    private void showlbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showlbl1MouseClicked
        // TODO add your handling code here:
        this.dispose();;
        Accounts a = new Accounts ();
        a.setVisible(true);
    }//GEN-LAST:event_showlbl1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
            
        
          String query_show_available = "SELECT id as SR, product_name as Products, quantity as Quantity FROM available";
        try{
            Class.forName(Connect.myDriver);
            Connect.con =DriverManager.getConnection(Connect.url,"sql7341636","ByYALuvP9g");
            Connect.st = Connect.con.createStatement();
            ResultSet rs = Connect.st.executeQuery(query_show_available);
            
            
                availableqtydatatable.setModel(DbUtils.resultSetToTableModel(rs));
            
                
               
            
        }catch(Exception e){
            System.out.println(e);
        }
        
        
       
                            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmDealItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmDealItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmDealItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        showDealers();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        panel_dealer.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showdealers();
        
    }//GEN-LAST:event_formWindowOpened

    private void searchboxtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxtxtKeyReleased
        // TODO add your handling code here: 
        
        DefaultTableModel table =  (DefaultTableModel)availableqtydatatable.getModel();
        String search = searchboxtxt.getText();
        TableRowSorter<DefaultTableModel> tr = new  TableRowSorter<DefaultTableModel>(table);
        availableqtydatatable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
   
        
        
    }//GEN-LAST:event_searchboxtxtKeyReleased

    private void orderlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderlblMouseClicked
        // TODO add your handling code here:
         this.dispose();
        OrderProduct os = new OrderProduct();
        os.setVisible(true);
    }//GEN-LAST:event_orderlblMouseClicked

    private void searchboxtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchboxtxtMouseClicked
        // TODO add your handling code here:
        searchboxtxt.setText("");
    }//GEN-LAST:event_searchboxtxtMouseClicked

    private void searchboxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxtxtActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();;
        Accounts a = new Accounts ();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        excelSheet();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        showSellProducts();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         panel_dealer.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DayDealStart;
    private com.toedter.calendar.JDateChooser DaySealEnd;
    private javax.swing.JLabel addlbl;
    private javax.swing.JLabel addlogolbl;
    private javax.swing.JTable availableqtydatatable;
    private com.toedter.calendar.JDateChooser billndate;
    private com.toedter.calendar.JDateChooser billsdate;
    private javax.swing.JComboBox<String> cmDeal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menupanel;
    private javax.swing.JLabel orderlbl;
    private javax.swing.JLabel orderlogo;
    private javax.swing.JPanel panel_dealer;
    private javax.swing.JTextField searchboxtxt;
    private javax.swing.JLabel sellblb;
    private javax.swing.JLabel selllogolbl;
    private javax.swing.JLabel showlbl;
    private javax.swing.JLabel showlbl1;
    private javax.swing.JLabel showlogo;
    // End of variables declaration//GEN-END:variables
}
